disabled_rules:
  - trailing_whitespace
  - identifier_name
  - line_length
  - switch_case_alignment
  
type_name:
  allowed_symbols: "_"

excluded:
  - Pods

whitelist_autocorrect:
  - opening_brace
  - vertical_whitespace
